const success = 'Success!';
const throwError = new Error(`something went wrong, please try again`);

export {
  success, throwError
}
